#+TITLE:README
#+AUTHOR: Karim Aziiev
#+EMAIL: karim.aziiev@gmail.com

* igist

** Requirements

+ Emacs >= 28.1
+ ivy (optional)
+ ghub
+ transient
- [[https://magit.vc/manual/forge/Token-Creation.html#Token-Creation][Github API token]]

** Installation

*** Manually

Download repository and it to your load path in your init file:

#+begin_src elisp :eval no

(add-to-list 'load-path "/path/to/igist)

(require 'igist)

#+end_src

*** With use-package and straight

#+begin_src elisp :eval no

(use-package igist
	:straight (igist
			       :repo "KarimAziev/igist"
			       :type git
			       :host github)
	:bind ((:map igist-edit-buffer-default-keymap
			         ("M-o" . igist-transient-api)
			         ("C-c C-c" . igist-save-current-gist)
			         ("C-c C-k" . kill-current-buffer)))
	:commands (igist-ivy-read-gists
			       igist-edit-gists
			       igist-refresh-current-gist
			       igist-read-filename
			       igist-read-description))

#+end_src

** Auth
You need to ensure that you have [[https://github.com/settings/tokens][a Github API token]] with scope ~gist~.

Assuming your Github username is "ziggy", you have created a token "012345abcdefgde", so you need to add such entry in one of files listed in the the variable ~auth-sources~ (~M-x describe-variable~ ~RET~ and type ~auth-sources~, usually it is =~/.authinfo= or =~/.authinfo.gpg=):

#+begin_example
machine api.github.com login ziggy^forge password 012345abcdefgde
#+end_example

You can read more in [[https://magit.vc/manual/forge/Token-Creation.html#Token-Creation][ghub]] manual as igist relies on the provided api. 

** Keymaps
** Usage

*** ~M-x igist-edit-gists~
Read user gists in minibuffer and open it in edit buffer.

*** Edit buffer commands:
**** ~igist-save-current-gist~
Save current gist.
**** ~igist-refresh-current-gist~
Refresh current ~gist.~
**** ~igist-read-filename~
Rename current gist without saving.
**** ~igist-read-description~
Update description for current gist without saving.
*** Edit buffer keymap

| Command                 | Key     |
|-------------------------+---------|
| igist-transient-api     | M-o     |
| igist-save-current-gist | C-c C-c |
| kill-current-buffer     | C-c C-k |
